### ISSUE TITLE
[Ruby] Loading concepts fails

### ISSUE THREAD

**Issue by mkllnk** [datafoodconsortium/connector-codegen#3]
Loading vocabularies fails with the old and new version of vocabularies. With the old version it shows an error in the parser:

https://github.com/datafoodconsortium/connector-codegen/blob/07ec67ec20b44cdcb3cbd8ebdb985b387da8293d/src/org/datafoodconsortium/connector/codegen/ruby/static/lib/datafoodconsortium/connector/skos_parser.rb#L87-L92

The parser tries to create a concept without giving it its mandatory semantic id.

I also tried the new files but encountered the same error as the current version of the ruby connector raises:

* https://github.com/datafoodconsortium/connector-ruby/issues/19

**Comment by lecoqlibre** [comment]
Hi @mkllnk can you try it using the [issue3 branch](https://github.com/datafoodconsortium/connector-codegen/tree/issue3) of this repo with the [codegen-issue3 branch](https://github.com/datafoodconsortium/data-model-uml/tree/codegen-issue3) of the data-model-uml repo?

**Comment by mkllnk** [comment]
Yes, that solves the issue. Can you merge?
